<a href="https://colab.research.google.com/github/dark-dev2475/Machine-learning-ai/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pandas library : used for data processing and anlaysis

pandas data frame:
two dimensional tabuar data structure with labeled aaxes

In [ ]:
import pandas as pd
import numpy as np

creating a pandas data frame

In [ ]:
#importing the boston  house price data
from sklearn.datasets import fetch_california_housing

In [ ]:
data=fetch_california_housing()
type(data)

sklearn.utils._bunch.Bunch

In [ ]:
print(data)

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]]), 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]), 'frame': None, 'target_names': ['MedHouseVal'], 'feature_names': ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude'], 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33 (1997) 291-297\n'}

In [ ]:
boston_df=pd.DataFrame(data.data,columns=data.feature_names)

In [ ]:
boston_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [ ]:
type(boston_df)

pandas.core.frame.DataFrame

imporing a data from csv file to pandas frame

In [ ]:
#csvfile t pandas dataframe
diabetes_df=pd.read_csv("/content/diabetes.csv")

In [ ]:
type(diabetes_df)

pandas.core.frame.DataFrame

In [ ]:
diabetes_df.head()
#it prints the first fivve data of the data frame

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
diabetes_df.shape

(768, 9)

importting a data set from excel file use this function

In [ ]:
#importing data from excel file to a pandas data frame
pd.read_excel('file path')

exporting a data frame to a csv file

In [ ]:
boston_df.to_csv('boston.csv')

exporting data frame to a excel file

df.to_excel('filename')

In [ ]:
#creating  a data frame with random values
random_df=pd.DataFrame(np.random.randint(1,1000000,(20,10)))

In [ ]:
random_df.head()

,0,1,2,3,4,5,6,7,8,9
0,945208,473953,615062,352361,300451,787178,609357,719845,50051,546699
1,177528,393289,173481,648953,916168,950524,978101,309082,210500,842306
2,849521,174471,141984,125776,511607,608058,526152,230405,1881,239186
3,628317,87844,695812,329288,251232,219109,512623,209020,318106,464300
4,873574,660377,918221,218170,767400,417883,870352,751511,41962,746823

In [ ]:
random_df.shape

(20, 10)

inspecting a data frame

In [ ]:
#finding the number ofrowws and columns
boston_df.shape

(20640, 8)

In [ ]:
#first fiev rows
boston_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [ ]:
#last five rows of df
boston_df.tail()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [ ]:
#informatiions about data frame
boston_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB

In [ ]:
boston_df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

In [ ]:
diabetes_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
#counting thee values based on the labels
diabetes_df.value_counts('Age')

Age
22    72
21    63
25    48
24    46
23    38
28    35
26    33
27    32
29    29
31    24
41    22
30    21
37    19
42    18
33    17
32    16
38    16
36    16
45    15
34    14
46    13
43    13
40    13
39    12
35    10
44     8
51     8
50     8
52     8
58     7
54     6
47     6
49     5
53     5
57     5
48     5
60     5
55     4
63     4
62     4
66     4
56     3
65     3
59     3
67     3
61     2
69     2
64     1
68     1
70     1
72     1
81     1
Name: count, dtype: int64

In [ ]:
#group the value based on the mean
diabetes_df.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

Statistical measure

In [ ]:
#this function gives us the number of values in each column
boston_df.count()

MedInc        20640
HouseAge      20640
AveRooms      20640
AveBedrms     20640
Population    20640
AveOccup      20640
Latitude      20640
Longitude     20640
dtype: int64

In [ ]:
#mean value->columnwise
boston_df.mean()

MedInc           3.870671
HouseAge        28.639486
AveRooms         5.429000
AveBedrms        1.096675
Population    1425.476744
AveOccup         3.070655
Latitude        35.631861
Longitude     -119.569704
dtype: float64

In [ ]:
#standard deviation->column wise
boston_df.std()

MedInc           1.899822
HouseAge        12.585558
AveRooms         2.474173
AveBedrms        0.473911
Population    1132.462122
AveOccup        10.386050
Latitude         2.135952
Longitude        2.003532
dtype: float64

In [ ]:
#minimum value ->columnwise
boston_df.min()

MedInc          0.499900
HouseAge        1.000000
AveRooms        0.846154
AveBedrms       0.333333
Population      3.000000
AveOccup        0.692308
Latitude       32.540000
Longitude    -124.350000
dtype: float64

In [ ]:
#maximum value
boston_df.max()

MedInc           15.000100
HouseAge         52.000000
AveRooms        141.909091
AveBedrms        34.066667
Population    35682.000000
AveOccup       1243.333333
Latitude         41.950000
Longitude      -114.310000
dtype: float64

In [ ]:
#all the stats for the data frame
boston_df.describe()  # target are the values which are not given initiaally o the data frame

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000

manipulating a data frame

In [ ]:
#adding  a column to a data frame
boston_df['Price']=data.target

In [ ]:
boston_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [ ]:
 #removing a row
 boston_df.drop(index=0,axis=0)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
5,4.0368,52.0,4.761658,1.103627,413.0,2.139896,37.85,-122.25,2.697
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [ ]:
#drop a column, these operations does not change the original data frame
boston_df.drop(columns='MedInc',axis=1)

,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
0,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...
20635,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [ ]:
# locate a row using the index value
boston_df.iloc[2]

MedInc          7.257400
HouseAge       52.000000
AveRooms        8.288136
AveBedrms       1.073446
Population    496.000000
AveOccup        2.802260
Latitude       37.850000
Longitude    -122.240000
Price           3.521000
Name: 2, dtype: float64

In [ ]:
boston_df.drop(index=0,axis=0,inplace=True)
# this is the function ehichh can rmove the entire row permanently

In [ ]:
#locating a paticular columns
boston_df.iloc[:,0]  #first columns

1        8.3014
2        7.2574
3        5.6431
4        3.8462
5        4.0368
          ...
20635    1.5603
20636    2.5568
20637    1.7000
20638    1.8672
20639    2.3886
Name: MedInc, Length: 20639, dtype: float64

Corelations :
1. positive
2. negative

relation of a column with another column

In [ ]:
boston_df.corr()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
MedInc,1.000000,-0.119164,0.326871,-0.062031,0.004946,0.018774,-0.079941,-0.015028,0.688000
HouseAge,-0.119164,1.000000,-0.153312,-0.077742,-0.296212,0.013194,0.011123,-0.108141,0.105536
AveRooms,0.326871,-0.153312,1.000000,0.847635,-0.072186,-0.004851,0.106361,-0.027501,0.151902
AveBedrms,-0.062031,-0.077742,0.847635,1.000000,-0.066206,-0.006182,0.069731,0.013335,-0.046690
Population,0.004946,-0.296212,-0.072186,-0.066206,1.000000,0.069862,-0.108740,0.099717,-0.024552
AveOccup,0.018774,0.013194,-0.004851,-0.006182,0.069862,1.000000,0.002369,0.002473,-0.023735
Latitude,-0.079941,0.011123,0.106361,0.069731,-0.108740,0.002369,1.000000,-0.924661,-0.144289
Longitude,-0.015028,-0.108141,-0.027501,0.013335,0.099717,0.002473,-0.924661,1.000000,-0.045837
Price,0.688000,0.105536,0.151902,-0.046690,-0.024552,-0.023735,-0.144289,-0.045837,1.000000